# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            vaibhavkhl
tagline:
url:              http://vaibhavkhl.in
paginate:         1
baseurl:          /
author:
  name:           Vaibhav Kohli
  url:            https://twitter.com/mdo
  email:          vaibhav.khl@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/vaibhavkhl/vaibhavkhl.github.io
